### ISSUE TITLE
Update License

### ISSUE THREAD

**Issue by hergaiety** [ember-a11y/ember-select-light#1]
The original repo this is forked from has a [copyright from Q2 (2016) of the Apache 2.0 License](https://github.com/ember-a11y/ember-select-light/blob/master/LICENSE.md). We need to interpret this and determine if we can either:
* Keep the license as is
* Update the license in a meaningful way
* Replace the license with MIT to match what other ember-a11y projects do

Perhaps we discover in this investigation that the existing license makes this fork impossible. If that's the case we'll need to recreate this from scratch and lose any existing users (primarily just Q2 at this point).

**Comment by hergaiety** [comment]
According to Melanie, it sounds like since this is a fork we can make any changes that we wish - including changing to a MIT license. So that's now what this Issue will be for :)

**Comment by MelSumner** [comment]
> The best answer is: it depends on the license of the original code. For example, if the original code is licensed under the GPL license, your modification must be distributed under the same license. But if the original code is distributed under BSD-license, you can choose any license you want for your modified version.

Based on what I've read, it seems fine to do in this instance. 

I think it might be polite to include a link to the original somewhere in the README, something like "originally published as X" or "forked from X" or something like that.
